/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cajerocel.vista;

import cajerocel.controlador.Consulta_Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */
public class FrmDinero extends javax.swing.JFrame {

    /**
     * Creates new form FrmDinero
     */
    public FrmDinero() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("VALORES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn20 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn51 = new javax.swing.JButton();
        btn76 = new javax.swing.JButton();
        btn101 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnOtroValor2 = new javax.swing.JButton();
        btnAtras2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn20.setText("20 $");
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        jPanel1.add(btn20);

        btn30.setText("30 $");
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });
        jPanel1.add(btn30);

        btn40.setText("40 $");
        btn40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn40ActionPerformed(evt);
            }
        });
        jPanel1.add(btn40);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(86, 36, 209));
        jLabel2.setText("CAJERO AUTOMATICO");

        jLabel1.setText("Valores de Retiro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btn51.setText("50 $");
        btn51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn51ActionPerformed(evt);
            }
        });
        jPanel3.add(btn51);

        btn76.setText("75 $");
        btn76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn76ActionPerformed(evt);
            }
        });
        jPanel3.add(btn76);

        btn101.setText("100 $");
        btn101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn101ActionPerformed(evt);
            }
        });
        jPanel3.add(btn101);

        btnOtroValor2.setText("Otro Valor");
        btnOtroValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtroValor2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnOtroValor2);

        btnAtras2.setText("Atras");
        btnAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnAtras2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtroValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtroValor2ActionPerformed
        // TODO add your handling code here:
         new FrmRetiro().setVisible(true);
    }//GEN-LAST:event_btnOtroValor2ActionPerformed

    private void btnAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras2ActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btnAtras2ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
        Consulta_Cuenta c = new Consulta_Cuenta();
          if(Consulta_Cuenta.cuenta.getSaldo()>20){
          JOptionPane.showMessageDialog(rootPane, "Usted a retirado: " +btn20.getText());
                double sal=20;
              
              Consulta_Cuenta.cuenta.setSaldo( Consulta_Cuenta.cuenta.getSaldo()-sal);
                JOptionPane.showMessageDialog(rootPane, "El saldo actual: " +Consulta_Cuenta.cuenta.getSaldo());
          }else{
            JOptionPane.showMessageDialog(rootPane, "No teien saldo suficiente ");
        
         }
          c.actualizar(Consulta_Cuenta.cuenta);
               
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed
        // TODO add your handling code here:
         Consulta_Cuenta c = new Consulta_Cuenta();
         if(Consulta_Cuenta.cuenta.getSaldo()>30){
         JOptionPane.showMessageDialog(rootPane, "Usted a retirado: " +btn30.getText());
                double sal=30;
              
               Consulta_Cuenta.cuenta.setSaldo( Consulta_Cuenta.cuenta.getSaldo()-sal);
                JOptionPane.showMessageDialog(rootPane, "El saldo actual: " +Consulta_Cuenta.cuenta.getSaldo());
                  }else{
            JOptionPane.showMessageDialog(rootPane, "No teien saldo suficiente ");
        
         }
          c.actualizar(Consulta_Cuenta.cuenta);
    }//GEN-LAST:event_btn30ActionPerformed

    private void btn40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn40ActionPerformed
        // TODO add your handling code here:
        Consulta_Cuenta c = new Consulta_Cuenta();
         if(Consulta_Cuenta.cuenta.getSaldo()>40){
         JOptionPane.showMessageDialog(rootPane, "Usted a retirado: " +btn40.getText());
                double sal=40;
              
                Consulta_Cuenta.cuenta.setSaldo( Consulta_Cuenta.cuenta.getSaldo()-sal);
                JOptionPane.showMessageDialog(rootPane, "El saldo actual: " +Consulta_Cuenta.cuenta.getSaldo());
                 }else{
            JOptionPane.showMessageDialog(rootPane, "No teien saldo suficiente ");
        
         }
          c.actualizar(Consulta_Cuenta.cuenta);
    }//GEN-LAST:event_btn40ActionPerformed

    private void btn51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn51ActionPerformed
        // TODO add your handling code here:
         Consulta_Cuenta c = new Consulta_Cuenta();
         if(Consulta_Cuenta.cuenta.getSaldo()>50){
         JOptionPane.showMessageDialog(rootPane, "Usted a retirado: " +btn51.getText());
                double sal=50;
              
              Consulta_Cuenta.cuenta.setSaldo( Consulta_Cuenta.cuenta.getSaldo()-sal);
                JOptionPane.showMessageDialog(rootPane, "El saldo actual: " +Consulta_Cuenta.cuenta.getSaldo());
                   }else{
            JOptionPane.showMessageDialog(rootPane, "No teien saldo suficiente ");
         }
          c.actualizar(Consulta_Cuenta.cuenta);
    }//GEN-LAST:event_btn51ActionPerformed

    private void btn76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn76ActionPerformed
        // TODO add your handling code here:
           Consulta_Cuenta c = new Consulta_Cuenta();
         if(Consulta_Cuenta.cuenta.getSaldo()>75){
         JOptionPane.showMessageDialog(rootPane, "Usted a retirado: " +btn76.getText());
                double sal=75;
              
                Consulta_Cuenta.cuenta.setSaldo( Consulta_Cuenta.cuenta.getSaldo()-sal);
                JOptionPane.showMessageDialog(rootPane, "El saldo actual: " +Consulta_Cuenta.cuenta.getSaldo());
                 }else{
            JOptionPane.showMessageDialog(rootPane, "No teien saldo suficiente ");
        
         }
         c.actualizar(Consulta_Cuenta.cuenta);
    }//GEN-LAST:event_btn76ActionPerformed

    private void btn101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn101ActionPerformed
        // TODO add your handling code here:
         Consulta_Cuenta c = new Consulta_Cuenta();
         if(Consulta_Cuenta.cuenta.getSaldo()>100){
         JOptionPane.showMessageDialog(rootPane, "Usted a retirado: " +btn101.getText());
                double sal=100;
              
                 Consulta_Cuenta.cuenta.setSaldo( Consulta_Cuenta.cuenta.getSaldo()-sal);
                JOptionPane.showMessageDialog(rootPane, "El saldo actual: " +Consulta_Cuenta.cuenta.getSaldo());
                 }else{
            JOptionPane.showMessageDialog(rootPane, "No teien saldo suficiente ");
         }
          c.actualizar(Consulta_Cuenta.cuenta);
    }//GEN-LAST:event_btn101ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn101;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn51;
    private javax.swing.JButton btn76;
    private javax.swing.JButton btnAtras2;
    private javax.swing.JButton btnOtroValor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
