/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cajerocel.vista;

import cajerocel.controlador.Consulta_Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */
public class FrmDeposito extends javax.swing.JFrame {

    /**
     * Creates new form FrmDeposito
     */
    public FrmDeposito() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("DEPOSITO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCorregir = new javax.swing.JButton();
        btnCorrecto = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        txtDepositar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(86, 36, 209));
        jLabel2.setText("CAJERO AUTOMATICO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 30, 267, 32);

        jLabel3.setText("Que cantidad de dinero  desea DEPOSITAR?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 200, 220, 50);

        btnCorregir.setMnemonic('C');
        btnCorregir.setText("Corregir");
        btnCorregir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorregirActionPerformed(evt);
            }
        });
        jPanel1.add(btnCorregir);
        btnCorregir.setBounds(260, 160, 90, 23);

        btnCorrecto.setMnemonic('C');
        btnCorrecto.setText("Correcto");
        btnCorrecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrectoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCorrecto);
        btnCorrecto.setBounds(260, 200, 90, 23);

        btnAtras.setMnemonic('A');
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras);
        btnAtras.setBounds(260, 240, 90, 23);

        txtDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepositarActionPerformed(evt);
            }
        });
        jPanel1.add(txtDepositar);
        txtDepositar.setBounds(60, 250, 160, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrador\\Documents\\NetBeansCel\\CajeroCel\\CajeroCel\\src\\PicsATM\\ATM2.jpeg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 80, 210, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCorrectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrectoActionPerformed
        Consulta_Cuenta c = new Consulta_Cuenta();        
        JOptionPane.showMessageDialog(rootPane, "Su deposito fue de: " +txtDepositar.getText());
                double sal=0;
                sal= Double.parseDouble(txtDepositar.getText());
             
                Consulta_Cuenta.cuenta.setSaldo( Consulta_Cuenta.cuenta.getSaldo()+sal);
                JOptionPane.showMessageDialog(rootPane, "El saldo actual: " +Consulta_Cuenta.cuenta.getSaldo());
              
               c.actualizar(Consulta_Cuenta.cuenta); 

    }//GEN-LAST:event_btnCorrectoActionPerformed

    private void txtDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepositarActionPerformed

    private void btnCorregirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorregirActionPerformed
        txtDepositar.setText("  ");
    }//GEN-LAST:event_btnCorregirActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCorrecto;
    private javax.swing.JButton btnCorregir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDepositar;
    // End of variables declaration//GEN-END:variables
}
